/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Kirthana Balasubramanian
 */
public class level_6 extends javax.swing.JFrame {

    /**
     * Creates new form level_6
     */
    int i=1;
    correct_wrong_audio a=new correct_wrong_audio();
    public level_6() {
        initComponents();
        
        jButton4.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 3, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("LEVEL 6");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 159, 120, -1));

        jLabel2.setFont(new java.awt.Font("Bernard MT Condensed", 3, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("OHHO..  BLANKS!!  (=_=)  CAN U FILL IT UP??   (@_@)  ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 204, -1, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel3.setText("Once upon a time, there lived a lion and a ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 305, -1, -1));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel4.setText("____________");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 305, -1, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel5.setText(". One day the lion was ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 305, -1, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel6.setText("____________");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(979, 305, -1, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel7.setText(". The");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1087, 305, -1, -1));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel8.setText("mouse started ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 339, -1, -1));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel9.setText("____________");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 339, -1, -1));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel10.setText("on it. The lion woke up. He caught up the mouse and was going to");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 339, -1, -1));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel11.setText("____________");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 339, 100, -1));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel12.setText(".");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1177, 339, 10, -1));

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel13.setText("The mouse requested for");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 373, -1, -1));

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel14.setText("____________");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 373, -1, -1));

        jLabel15.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel15.setText(". The lion let him go. After some days the lion caught in a");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 373, -1, -1));

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel16.setText("________");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1077, 373, -1, -1));

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel17.setText(".");
        jLabel17.setToolTipText("");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1148, 373, -1, -1));

        jLabel18.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel18.setText("The mouse cut the net with his");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 407, -1, -1));

        jLabel19.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel19.setText("____________");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 407, -1, -1));

        jLabel20.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel20.setText(". The lion was free. He");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 407, -1, -1));

        jLabel21.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel21.setText("____________");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 407, -1, -1));

        jLabel22.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel22.setText("the mouse.");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 407, -1, -1));

        jLabel23.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel23.setText("MORAL :   Do");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 468, -1, -1));

        jLabel24.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel24.setText("________");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 468, -1, -1));

        jLabel25.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel25.setText("have");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 468, -1, -1));

        jLabel26.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel26.setText("________");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 468, -1, -1));

        jLabel27.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel27.setText("!!");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 468, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(102, 0, 153));
        jTextField1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("playing");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 542, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(102, 0, 153));
        jTextField2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("kill");
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 542, -1, -1));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(102, 0, 153));
        jTextField3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("teeth");
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 542, -1, -1));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(102, 0, 153));
        jTextField4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("mouse");
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 542, -1, -1));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(102, 0, 153));
        jTextField5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("pleased");
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 542, -1, -1));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(102, 0, 153));
        jTextField6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setText("good");
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField6MouseClicked(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 542, -1, -1));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(102, 0, 153));
        jTextField7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setText("jumping");
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField7MouseClicked(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(975, 542, -1, -1));

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(102, 0, 153));
        jTextField8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setText("forgiveness");
        jTextField8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField8MouseClicked(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 582, -1, -1));

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(102, 0, 153));
        jTextField9.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setText("sleeping");
        jTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField9MouseClicked(evt);
            }
        });
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 582, -1, -1));

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(102, 0, 153));
        jTextField10.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.setText("thanked");
        jTextField10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField10MouseClicked(evt);
            }
        });
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 582, -1, -1));

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(102, 0, 153));
        jTextField11.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 255, 255));
        jTextField11.setText("walking");
        jTextField11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField11MouseClicked(evt);
            }
        });
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(844, 582, -1, -1));

        jTextField12.setEditable(false);
        jTextField12.setBackground(new java.awt.Color(102, 0, 153));
        jTextField12.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));
        jTextField12.setText("good");
        jTextField12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField12MouseClicked(evt);
            }
        });
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 622, -1, -1));

        jTextField13.setEditable(false);
        jTextField13.setBackground(new java.awt.Color(102, 0, 153));
        jTextField13.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(255, 255, 255));
        jTextField13.setText("help");
        jTextField13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField13MouseClicked(evt);
            }
        });
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 622, -1, -1));

        jTextField14.setEditable(false);
        jTextField14.setBackground(new java.awt.Color(102, 0, 153));
        jTextField14.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(255, 255, 255));
        jTextField14.setText("net");
        jTextField14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField14MouseClicked(evt);
            }
        });
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 622, -1, -1));

        jTextField15.setEditable(false);
        jTextField15.setBackground(new java.awt.Color(102, 0, 153));
        jTextField15.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(255, 255, 255));
        jTextField15.setText("hit");
        jTextField15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField15MouseClicked(evt);
            }
        });
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 622, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jButton1.setText("DONE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 700, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jButton2.setText("RETRY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 700, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/prev_button.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 468, 165, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/next_button.jpg"))); // NOI18N
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 460, 170, 30));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/home_button.jpg"))); // NOI18N
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 680, 70, 80));
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 1030));
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 460, 70, 20));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/levelback8.png"))); // NOI18N
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:         
        
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:         playing
        if(jLabel4.getText().equals("____________"))
        {
            jLabel4.setForeground(new Color(102,0,153));
            jLabel4.setText(jTextField1.getText());
            jTextField1.setEnabled(false);
            return;
            
        }
        
        if(jLabel6.getText().equals("____________"))
        {
            jLabel6.setForeground(new Color(102,0,153));
            jLabel6.setText(jTextField1.getText());
            jTextField1.setEnabled(false);
            return;
            
        }
        
        if(jLabel9.getText().equals("____________"))
        {
            jLabel9.setForeground(new Color(102,0,153));
            jLabel9.setText(jTextField1.getText());
            jTextField1.setEnabled(false);
            return;
            
        }
        
        if(jLabel11.getText().equals("____________"))
        {
            jLabel11.setForeground(new Color(102,0,153));
            jLabel11.setText(jTextField1.getText());
            jTextField1.setEnabled(false);
            return;
            
        }
        
        if(jLabel14.getText().equals("____________"))
        {
            jLabel14.setForeground(new Color(102,0,153));
            jLabel14.setText(jTextField1.getText());
            jTextField1.setEnabled(false);
            return;
            
        }
        
        if(jLabel16.getText().equals("________"))
        {
            jLabel16.setForeground(new Color(102,0,153));
            jLabel16.setText(jTextField1.getText());
            jTextField1.setEnabled(false);
            return;
            
        }
        
        if(jLabel19.getText().equals("____________"))
        {
            jLabel19.setForeground(new Color(102,0,153));
            jLabel19.setText(jTextField1.getText());
            jTextField1.setEnabled(false);
            return;
            
        }
        
        if(jLabel21.getText().equals("____________"))
        {
            jLabel21.setForeground(new Color(102,0,153));
            jLabel21.setText(jTextField1.getText());
            jTextField1.setEnabled(false);
            return;
            
        }
        
        if(jLabel24.getText().equals("________"))
        {
            jLabel24.setForeground(new Color(102,0,153));
            jLabel24.setText(jTextField1.getText());
            jTextField1.setEnabled(false);
            return;
            
        }
        
        if(jLabel26.getText().equals("________"))
        {
            jLabel26.setForeground(new Color(102,0,153));
            jLabel26.setText(jTextField1.getText());
            jTextField1.setEnabled(false);
            return;
            
        }
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // TODO add your handling code here:   kill
        if(jLabel4.getText().equals("____________"))
        {
            jLabel4.setForeground(new Color(102,0,153));
            jLabel4.setText(jTextField2.getText());
            jTextField2.setEnabled(false);
            return;
            
        }
        
        if(jLabel6.getText().equals("____________"))
        {
            jLabel6.setForeground(new Color(102,0,153));
            jLabel6.setText(jTextField2.getText());
            jTextField2.setEnabled(false);
            return;
            
        }
        
        if(jLabel9.getText().equals("____________"))
        {
            jLabel9.setForeground(new Color(102,0,153));
            jLabel9.setText(jTextField2.getText());
            jTextField2.setEnabled(false);
            return;
            
        }
        
        if(jLabel11.getText().equals("____________"))
        {
            jLabel11.setForeground(new Color(102,0,153));
            jLabel11.setText(jTextField2.getText());
            jTextField2.setEnabled(false);
            return;
            
        }
        
        if(jLabel14.getText().equals("____________"))
        {
            jLabel14.setForeground(new Color(102,0,153));
            jLabel14.setText(jTextField2.getText());
            jTextField2.setEnabled(false);
            return;
            
        }
        
        if(jLabel16.getText().equals("________"))
        {
            jLabel16.setForeground(new Color(102,0,153));
            jLabel16.setText(jTextField2.getText());
            jTextField2.setEnabled(false);
            return;
            
        }
        
        if(jLabel19.getText().equals("____________"))
        {
            jLabel19.setForeground(new Color(102,0,153));
            jLabel19.setText(jTextField2.getText());
            jTextField2.setEnabled(false);
            return;
            
        }
        
        if(jLabel21.getText().equals("____________"))
        {
            jLabel21.setForeground(new Color(102,0,153));
            jLabel21.setText(jTextField2.getText());
            jTextField2.setEnabled(false);
            return;
            
        }
        
        if(jLabel24.getText().equals("________"))
        {
            jLabel24.setForeground(new Color(102,0,153));
            jLabel24.setText(jTextField2.getText());
            jTextField2.setEnabled(false);
            return;
            
        }
        
        if(jLabel26.getText().equals("________"))
        {
            jLabel26.setForeground(new Color(102,0,153));
            jLabel26.setText(jTextField2.getText());
            jTextField2.setEnabled(false);
            return;
            
        }
        
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        // TODO add your handling code here:    teeth
        if(jLabel4.getText().equals("____________"))
        {
            jLabel4.setForeground(new Color(102,0,153));
            jLabel4.setText(jTextField3.getText());
            jTextField3.setEnabled(false);
            return;
            
        }
        
        if(jLabel6.getText().equals("____________"))
        {
            jLabel6.setForeground(new Color(102,0,153));
            jLabel6.setText(jTextField3.getText());
            jTextField3.setEnabled(false);
            return;
            
        }
        
        if(jLabel9.getText().equals("____________"))
        {
            jLabel9.setForeground(new Color(102,0,153));
            jLabel9.setText(jTextField3.getText());
            jTextField3.setEnabled(false);
            return;
            
        }
        
        if(jLabel11.getText().equals("____________"))
        {
            jLabel11.setForeground(new Color(102,0,153));
            jLabel11.setText(jTextField3.getText());
            jTextField3.setEnabled(false);
            return;
            
        }
        
        if(jLabel14.getText().equals("____________"))
        {
            jLabel14.setForeground(new Color(102,0,153));
            jLabel14.setText(jTextField3.getText());
            jTextField3.setEnabled(false);
            return;
            
        }
        
        if(jLabel16.getText().equals("________"))
        {
            jLabel16.setForeground(new Color(102,0,153));
            jLabel16.setText(jTextField3.getText());
            jTextField3.setEnabled(false);
            return;
            
        }
        
        if(jLabel19.getText().equals("____________"))
        {
            jLabel19.setForeground(new Color(102,0,153));
            jLabel19.setText(jTextField3.getText());
            jTextField3.setEnabled(false);
            return;
            
        }
        
        if(jLabel21.getText().equals("____________"))
        {
            jLabel21.setForeground(new Color(102,0,153));
            jLabel21.setText(jTextField3.getText());
            jTextField3.setEnabled(false);
            return;
            
        }
        
        if(jLabel24.getText().equals("________"))
        {
            jLabel24.setForeground(new Color(102,0,153));
            jLabel24.setText(jTextField3.getText());
            jTextField3.setEnabled(false);
            return;
            
        }
        
        if(jLabel26.getText().equals("________"))
        {
            jLabel26.setForeground(new Color(102,0,153));
            jLabel26.setText(jTextField3.getText());
            jTextField3.setEnabled(false);
            return;
            
        }
    }//GEN-LAST:event_jTextField3MouseClicked

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        // TODO add your handling code here:    mouse
        if(jLabel4.getText().equals("____________"))
        {
            jLabel4.setForeground(new Color(102,0,153));
            jLabel4.setText(jTextField4.getText());
            jTextField4.setEnabled(false);
            return;
            
        }
        
        if(jLabel6.getText().equals("____________"))
        {
            jLabel6.setForeground(new Color(102,0,153));
            jLabel6.setText(jTextField4.getText());
            jTextField4.setEnabled(false);
            return;
            
        }
        
        if(jLabel9.getText().equals("____________"))
        {
            jLabel9.setForeground(new Color(102,0,153));
            jLabel9.setText(jTextField4.getText());
            jTextField4.setEnabled(false);
            return;
            
        }
        
        if(jLabel11.getText().equals("____________"))
        {
            jLabel11.setForeground(new Color(102,0,153));
            jLabel11.setText(jTextField4.getText());
            jTextField4.setEnabled(false);
            return;
            
        }
        
        if(jLabel14.getText().equals("____________"))
        {
            jLabel14.setForeground(new Color(102,0,153));
            jLabel14.setText(jTextField4.getText());
            jTextField4.setEnabled(false);
            return;
            
        }
        
        if(jLabel16.getText().equals("________"))
        {
            jLabel16.setForeground(new Color(102,0,153));
            jLabel16.setText(jTextField4.getText());
            jTextField4.setEnabled(false);
            return;
            
        }
        
        if(jLabel19.getText().equals("____________"))
        {
            jLabel19.setForeground(new Color(102,0,153));
            jLabel19.setText(jTextField4.getText());
            jTextField4.setEnabled(false);
            return;
            
        }
        
        if(jLabel21.getText().equals("____________"))
        {
            jLabel21.setForeground(new Color(102,0,153));
            jLabel21.setText(jTextField4.getText());
            jTextField4.setEnabled(false);
            return;
            
        }
        
        if(jLabel24.getText().equals("________"))
        {
            jLabel24.setForeground(new Color(102,0,153));
            jLabel24.setText(jTextField4.getText());
            jTextField4.setEnabled(false);
            return;
            
        }
        
        if(jLabel26.getText().equals("________"))
        {
            jLabel26.setForeground(new Color(102,0,153));
            jLabel26.setText(jTextField4.getText());
            jTextField4.setEnabled(false);
            return;
            
        }
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        // TODO add your handling code here:    pleased
        if(jLabel4.getText().equals("____________"))
        {
            jLabel4.setForeground(new Color(102,0,153));
            jLabel4.setText(jTextField5.getText());
            jTextField5.setEnabled(false);
            return;
            
        }
        
        if(jLabel6.getText().equals("____________"))
        {
            jLabel6.setForeground(new Color(102,0,153));
            jLabel6.setText(jTextField5.getText());
            jTextField5.setEnabled(false);
            return;
            
        }
        
        if(jLabel9.getText().equals("____________"))
        {
            jLabel9.setForeground(new Color(102,0,153));
            jLabel9.setText(jTextField5.getText());
            jTextField5.setEnabled(false);
            return;
            
        }
        
        if(jLabel11.getText().equals("____________"))
        {
            jLabel11.setForeground(new Color(102,0,153));
            jLabel11.setText(jTextField5.getText());
            jTextField5.setEnabled(false);
            return;
            
        }
        
        if(jLabel14.getText().equals("____________"))
        {
            jLabel14.setForeground(new Color(102,0,153));
            jLabel14.setText(jTextField5.getText());
            jTextField5.setEnabled(false);
            return;
            
        }
        
        if(jLabel16.getText().equals("________"))
        {
            jLabel16.setForeground(new Color(102,0,153));
            jLabel16.setText(jTextField5.getText());
            jTextField5.setEnabled(false);
            return;
            
        }
        
        if(jLabel19.getText().equals("____________"))
        {
            jLabel19.setForeground(new Color(102,0,153));
            jLabel19.setText(jTextField5.getText());
            jTextField5.setEnabled(false);
            return;
            
        }
        
        if(jLabel21.getText().equals("____________"))
        {
            jLabel21.setForeground(new Color(102,0,153));
            jLabel21.setText(jTextField5.getText());
            jTextField5.setEnabled(false);
            return;
            
        }
        
        if(jLabel24.getText().equals("________"))
        {
            jLabel24.setForeground(new Color(102,0,153));
            jLabel24.setText(jTextField5.getText());
            jTextField5.setEnabled(false);
            return;
            
        }
        
        if(jLabel26.getText().equals("________"))
        {
            jLabel26.setForeground(new Color(102,0,153));
            jLabel26.setText(jTextField5.getText());
            jTextField5.setEnabled(false);
            return;
            
        }
    }//GEN-LAST:event_jTextField5MouseClicked

    private void jTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseClicked
        // TODO add your handling code here:      good
        if(jLabel4.getText().equals("____________"))
        {
            jLabel4.setForeground(new Color(102,0,153));
            jLabel4.setText(jTextField6.getText());
            jTextField6.setEnabled(false);
            return;
            
        }
        
        if(jLabel6.getText().equals("____________"))
        {
            jLabel6.setForeground(new Color(102,0,153));
            jLabel6.setText(jTextField6.getText());
            jTextField6.setEnabled(false);
            return;
            
        }
        
        if(jLabel9.getText().equals("____________"))
        {
            jLabel9.setForeground(new Color(102,0,153));
            jLabel9.setText(jTextField6.getText());
            jTextField6.setEnabled(false);
            return;
            
        }
        
        if(jLabel11.getText().equals("____________"))
        {
            jLabel11.setForeground(new Color(102,0,153));
            jLabel11.setText(jTextField6.getText());
            jTextField6.setEnabled(false);
            return;
            
        }
        
        if(jLabel14.getText().equals("____________"))
        {
            jLabel14.setForeground(new Color(102,0,153));
            jLabel14.setText(jTextField6.getText());
            jTextField6.setEnabled(false);
            return;
            
        }
        
        if(jLabel16.getText().equals("________"))
        {
            jLabel16.setForeground(new Color(102,0,153));
            jLabel16.setText(jTextField6.getText());
            jTextField6.setEnabled(false);
            return;
            
        }
        
        if(jLabel19.getText().equals("____________"))
        {
            jLabel19.setForeground(new Color(102,0,153));
            jLabel19.setText(jTextField6.getText());
            jTextField6.setEnabled(false);
            return;
            
        }
        
        if(jLabel21.getText().equals("____________"))
        {
            jLabel21.setForeground(new Color(102,0,153));
            jLabel21.setText(jTextField6.getText());
            jTextField6.setEnabled(false);
            return;
            
        }
        
        if(jLabel24.getText().equals("________"))
        {
            jLabel24.setForeground(new Color(102,0,153));
            jLabel24.setText(jTextField6.getText());
            jTextField6.setEnabled(false);
            return;
            
        }
        
        if(jLabel26.getText().equals("________"))
        {
            jLabel26.setForeground(new Color(102,0,153));
            jLabel26.setText(jTextField6.getText());
            jTextField6.setEnabled(false);
            return;
            
        }
    }//GEN-LAST:event_jTextField6MouseClicked

    private void jTextField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseClicked
        // TODO add your handling code here:        jumping
        if(jLabel4.getText().equals("____________"))
        {
            jLabel4.setForeground(new Color(102,0,153));
            jLabel4.setText(jTextField7.getText());
            jTextField7.setEnabled(false);
            return;
            
        }
        
        if(jLabel6.getText().equals("____________"))
        {
            jLabel6.setForeground(new Color(102,0,153));
            jLabel6.setText(jTextField7.getText());
            jTextField7.setEnabled(false);
            return;
            
        }
        
        if(jLabel9.getText().equals("____________"))
        {
            jLabel9.setForeground(new Color(102,0,153));
            jLabel9.setText(jTextField7.getText());
            jTextField7.setEnabled(false);
            return;
            
        }
        
        if(jLabel11.getText().equals("____________"))
        {
            jLabel11.setForeground(new Color(102,0,153));
            jLabel11.setText(jTextField7.getText());
            jTextField7.setEnabled(false);
            return;
            
        }
        
        if(jLabel14.getText().equals("____________"))
        {
            jLabel14.setForeground(new Color(102,0,153));
            jLabel14.setText(jTextField7.getText());
            jTextField7.setEnabled(false);
            return;
            
        }
        
        if(jLabel16.getText().equals("________"))
        {
            jLabel16.setForeground(new Color(102,0,153));
            jLabel16.setText(jTextField7.getText());
            jTextField7.setEnabled(false);
            return;
            
        }
        
        if(jLabel19.getText().equals("____________"))
        {
            jLabel19.setForeground(new Color(102,0,153));
            jLabel19.setText(jTextField7.getText());
            jTextField7.setEnabled(false);
            return;
            
        }
        
        if(jLabel21.getText().equals("____________"))
        {
            jLabel21.setForeground(new Color(102,0,153));
            jLabel21.setText(jTextField7.getText());
            jTextField7.setEnabled(false);
            return;
            
        }
        
        if(jLabel24.getText().equals("________"))
        {
            jLabel24.setForeground(new Color(102,0,153));
            jLabel24.setText(jTextField7.getText());
            jTextField7.setEnabled(false);
            return;
            
        }
        
        if(jLabel26.getText().equals("________"))
        {
            jLabel26.setForeground(new Color(102,0,153));
            jLabel26.setText(jTextField7.getText());
            jTextField7.setEnabled(false);
            return;
            
        }
    }//GEN-LAST:event_jTextField7MouseClicked

    private void jTextField8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MouseClicked
        // TODO add your handling code here:      forgiveness
        if(jLabel4.getText().equals("____________"))
        {
            jLabel4.setForeground(new Color(102,0,153));
            jLabel4.setText(jTextField8.getText());
            jTextField8.setEnabled(false);
            return;
            
        }
        
        if(jLabel6.getText().equals("____________"))
        {
            jLabel6.setForeground(new Color(102,0,153));
            jLabel6.setText(jTextField8.getText());
            jTextField8.setEnabled(false);
            return;
            
        }
        
        if(jLabel9.getText().equals("____________"))
        {
            jLabel9.setForeground(new Color(102,0,153));
            jLabel9.setText(jTextField8.getText());
            jTextField8.setEnabled(false);
            return;
            
        }
        
        if(jLabel11.getText().equals("____________"))
        {
            jLabel11.setForeground(new Color(102,0,153));
            jLabel11.setText(jTextField8.getText());
            jTextField8.setEnabled(false);
            return;
            
        }
        
        if(jLabel14.getText().equals("____________"))
        {
            jLabel14.setForeground(new Color(102,0,153));
            jLabel14.setText(jTextField8.getText());
            jTextField8.setEnabled(false);
            return;
            
        }
        
        if(jLabel16.getText().equals("________"))
        {
            jLabel16.setForeground(new Color(102,0,153));
            jLabel16.setText(jTextField8.getText());
            jTextField8.setEnabled(false);
            return;
            
        }
        
        if(jLabel19.getText().equals("____________"))
        {
            jLabel19.setForeground(new Color(102,0,153));
            jLabel19.setText(jTextField8.getText());
            jTextField8.setEnabled(false);
            return;
            
        }
        
        if(jLabel21.getText().equals("____________"))
        {
            jLabel21.setForeground(new Color(102,0,153));
            jLabel21.setText(jTextField8.getText());
            jTextField8.setEnabled(false);
            return;
            
        }
        
        if(jLabel24.getText().equals("________"))
        {
            jLabel24.setForeground(new Color(102,0,153));
            jLabel24.setText(jTextField8.getText());
            jTextField8.setEnabled(false);
            return;
            
        }
        
        if(jLabel26.getText().equals("________"))
        {
            jLabel26.setForeground(new Color(102,0,153));
            jLabel26.setText(jTextField8.getText());
            jTextField8.setEnabled(false);
            return;
            
        }
    }//GEN-LAST:event_jTextField8MouseClicked

    private void jTextField9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseClicked
        // TODO add your handling code here:        sleeping
        if(jLabel4.getText().equals("____________"))
        {
            jLabel4.setForeground(new Color(102,0,153));
            jLabel4.setText(jTextField9.getText());
            jTextField9.setEnabled(false);
            return;
            
        }
        
        if(jLabel6.getText().equals("____________"))
        {
            jLabel6.setForeground(new Color(102,0,153));
            jLabel6.setText(jTextField9.getText());
            jTextField9.setEnabled(false);
            return;
            
        }
        
        if(jLabel9.getText().equals("____________"))
        {
            jLabel9.setForeground(new Color(102,0,153));
            jLabel9.setText(jTextField9.getText());
            jTextField9.setEnabled(false);
            return;
            
        }
        
        if(jLabel11.getText().equals("____________"))
        {
            jLabel11.setForeground(new Color(102,0,153));
            jLabel11.setText(jTextField9.getText());
            jTextField9.setEnabled(false);
            return;
            
        }
        
        if(jLabel14.getText().equals("____________"))
        {
            jLabel14.setForeground(new Color(102,0,153));
            jLabel14.setText(jTextField9.getText());
            jTextField9.setEnabled(false);
            return;
            
        }
        
        if(jLabel16.getText().equals("________"))
        {
            jLabel16.setForeground(new Color(102,0,153));
            jLabel16.setText(jTextField9.getText());
            jTextField9.setEnabled(false);
            return;
            
        }
        
        if(jLabel19.getText().equals("____________"))
        {
            jLabel19.setForeground(new Color(102,0,153));
            jLabel19.setText(jTextField9.getText());
            jTextField9.setEnabled(false);
            return;
            
        }
        
        if(jLabel21.getText().equals("____________"))
        {
            jLabel21.setForeground(new Color(102,0,153));
            jLabel21.setText(jTextField9.getText());
            jTextField9.setEnabled(false);
            return;
            
        }
        
        if(jLabel24.getText().equals("________"))
        {
            jLabel24.setForeground(new Color(102,0,153));
            jLabel24.setText(jTextField9.getText());
            jTextField9.setEnabled(false);
            return;
            
        }
        
        if(jLabel26.getText().equals("________"))
        {
            jLabel26.setForeground(new Color(102,0,153));
            jLabel26.setText(jTextField9.getText());
            jTextField9.setEnabled(false);
            return;
            
        }
    }//GEN-LAST:event_jTextField9MouseClicked

    private void jTextField10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField10MouseClicked
        // TODO add your handling code here:    thanked
        if(jLabel4.getText().equals("____________"))
        {
            jLabel4.setForeground(new Color(102,0,153));
            jLabel4.setText(jTextField10.getText());
            jTextField10.setEnabled(false);
            return;
            
        }
        
        if(jLabel6.getText().equals("____________"))
        {
            jLabel6.setForeground(new Color(102,0,153));
            jLabel6.setText(jTextField10.getText());
            jTextField10.setEnabled(false);
            return;
            
        }
        
        if(jLabel9.getText().equals("____________"))
        {
            jLabel9.setForeground(new Color(102,0,153));
            jLabel9.setText(jTextField10.getText());
            jTextField10.setEnabled(false);
            return;
            
        }
        
        if(jLabel11.getText().equals("____________"))
        {
            jLabel11.setForeground(new Color(102,0,153));
            jLabel11.setText(jTextField10.getText());
            jTextField10.setEnabled(false);
            return;
            
        }
        
        if(jLabel14.getText().equals("____________"))
        {
            jLabel14.setForeground(new Color(102,0,153));
            jLabel14.setText(jTextField10.getText());
            jTextField10.setEnabled(false);
            return;
            
        }
        
        if(jLabel16.getText().equals("________"))
        {
            jLabel16.setForeground(new Color(102,0,153));
            jLabel16.setText(jTextField10.getText());
            jTextField10.setEnabled(false);
            return;
            
        }
        
        if(jLabel19.getText().equals("____________"))
        {
            jLabel19.setForeground(new Color(102,0,153));
            jLabel19.setText(jTextField10.getText());
            jTextField10.setEnabled(false);
            return;
            
        }
        
        if(jLabel21.getText().equals("____________"))
        {
            jLabel21.setForeground(new Color(102,0,153));
            jLabel21.setText(jTextField10.getText());
            jTextField10.setEnabled(false);
            return;
            
        }
        
        if(jLabel24.getText().equals("________"))
        {
            jLabel24.setForeground(new Color(102,0,153));
            jLabel24.setText(jTextField10.getText());
            jTextField10.setEnabled(false);
            return;
            
        }
        
        if(jLabel26.getText().equals("________"))
        {
            jLabel26.setForeground(new Color(102,0,153));
            jLabel26.setText(jTextField10.getText());
            jTextField10.setEnabled(false);
            return;
            
        }
    }//GEN-LAST:event_jTextField10MouseClicked

    private void jTextField11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField11MouseClicked
        // TODO add your handling code here:          walking
        if(jLabel4.getText().equals("____________"))
        {
            jLabel4.setForeground(new Color(102,0,153));
            jLabel4.setText(jTextField11.getText());
            jTextField11.setEnabled(false);
            return;
            
        }
        
        if(jLabel6.getText().equals("____________"))
        {
            jLabel6.setForeground(new Color(102,0,153));
            jLabel6.setText(jTextField11.getText());
            jTextField11.setEnabled(false);
            return;
            
        }
        
        if(jLabel9.getText().equals("____________"))
        {
            jLabel9.setForeground(new Color(102,0,153));
            jLabel9.setText(jTextField11.getText());
            jTextField11.setEnabled(false);
            return;
            
        }
        
        if(jLabel11.getText().equals("____________"))
        {
            jLabel11.setForeground(new Color(102,0,153));
            jLabel11.setText(jTextField11.getText());
            jTextField11.setEnabled(false);
            return;
            
        }
        
        if(jLabel14.getText().equals("____________"))
        {
            jLabel14.setForeground(new Color(102,0,153));
            jLabel14.setText(jTextField11.getText());
            jTextField11.setEnabled(false);
            return;
            
        }
        
        if(jLabel16.getText().equals("________"))
        {
            jLabel16.setForeground(new Color(102,0,153));
            jLabel16.setText(jTextField11.getText());
            jTextField11.setEnabled(false);
            return;
            
        }
        
        if(jLabel19.getText().equals("____________"))
        {
            jLabel19.setForeground(new Color(102,0,153));
            jLabel19.setText(jTextField11.getText());
            jTextField11.setEnabled(false);
            return;
            
        }
        
        if(jLabel21.getText().equals("____________"))
        {
            jLabel21.setForeground(new Color(102,0,153));
            jLabel21.setText(jTextField11.getText());
            jTextField11.setEnabled(false);
            return;
            
        }
        
        if(jLabel24.getText().equals("________"))
        {
            jLabel24.setForeground(new Color(102,0,153));
            jLabel24.setText(jTextField11.getText());
            jTextField11.setEnabled(false);
            return;
            
        }
        
        if(jLabel26.getText().equals("________"))
        {
            jLabel26.setForeground(new Color(102,0,153));
            jLabel26.setText(jTextField11.getText());
            jTextField11.setEnabled(false);
            return;
            
        }
    }//GEN-LAST:event_jTextField11MouseClicked

    private void jTextField12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField12MouseClicked
        // TODO add your handling code here:      good
        if(jLabel4.getText().equals("____________"))
        {
            jLabel4.setForeground(new Color(102,0,153));
            jLabel4.setText(jTextField12.getText());
            jTextField12.setEnabled(false);
            return;
            
        }
        
        if(jLabel6.getText().equals("____________"))
        {
            jLabel6.setForeground(new Color(102,0,153));
            jLabel6.setText(jTextField12.getText());
            jTextField12.setEnabled(false);
            return;
            
        }
        
        if(jLabel9.getText().equals("____________"))
        {
            jLabel9.setForeground(new Color(102,0,153));
            jLabel9.setText(jTextField12.getText());
            jTextField12.setEnabled(false);
            return;
            
        }
        
        if(jLabel11.getText().equals("____________"))
        {
            jLabel11.setForeground(new Color(102,0,153));
            jLabel11.setText(jTextField12.getText());
            jTextField12.setEnabled(false);
            return;
            
        }
        
        if(jLabel14.getText().equals("____________"))
        {
            jLabel14.setForeground(new Color(102,0,153));
            jLabel14.setText(jTextField12.getText());
            jTextField12.setEnabled(false);
            return;
            
        }
        
        if(jLabel16.getText().equals("________"))
        {
            jLabel16.setForeground(new Color(102,0,153));
            jLabel16.setText(jTextField12.getText());
            jTextField12.setEnabled(false);
            return;
            
        }
        
        if(jLabel19.getText().equals("____________"))
        {
            jLabel19.setForeground(new Color(102,0,153));
            jLabel19.setText(jTextField12.getText());
            jTextField12.setEnabled(false);
            return;
            
        }
        
        if(jLabel21.getText().equals("____________"))
        {
            jLabel21.setForeground(new Color(102,0,153));
            jLabel21.setText(jTextField12.getText());
            jTextField12.setEnabled(false);
            return;
            
        }
        
        if(jLabel24.getText().equals("________"))
        {
            jLabel24.setForeground(new Color(102,0,153));
            jLabel24.setText(jTextField12.getText());
            jTextField12.setEnabled(false);
            return;
            
        }
        
        if(jLabel26.getText().equals("________"))
        {
            jLabel26.setForeground(new Color(102,0,153));
            jLabel26.setText(jTextField12.getText());
            jTextField12.setEnabled(false);
            return;
            
        }
    }//GEN-LAST:event_jTextField12MouseClicked

    private void jTextField13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField13MouseClicked
        // TODO add your handling code here:           help
        if(jLabel4.getText().equals("____________"))
        {
            jLabel4.setForeground(new Color(102,0,153));
            jLabel4.setText(jTextField13.getText());
            jTextField13.setEnabled(false);
            return;
            
        }
        
        if(jLabel6.getText().equals("____________"))
        {
            jLabel6.setForeground(new Color(102,0,153));
            jLabel6.setText(jTextField13.getText());
            jTextField13.setEnabled(false);
            return;
            
        }
        
        if(jLabel9.getText().equals("____________"))
        {
            jLabel9.setForeground(new Color(102,0,153));
            jLabel9.setText(jTextField13.getText());
            jTextField13.setEnabled(false);
            return;
            
        }
        
        if(jLabel11.getText().equals("____________"))
        {
            jLabel11.setForeground(new Color(102,0,153));
            jLabel11.setText(jTextField13.getText());
            jTextField13.setEnabled(false);
            return;
            
        }
        
        if(jLabel14.getText().equals("____________"))
        {
            jLabel14.setForeground(new Color(102,0,153));
            jLabel14.setText(jTextField13.getText());
            jTextField13.setEnabled(false);
            return;
            
        }
        
        if(jLabel16.getText().equals("________"))
        {
            jLabel16.setForeground(new Color(102,0,153));
            jLabel16.setText(jTextField13.getText());
            jTextField13.setEnabled(false);
            return;
            
        }
        
        if(jLabel19.getText().equals("____________"))
        {
            jLabel19.setForeground(new Color(102,0,153));
            jLabel19.setText(jTextField13.getText());
            jTextField13.setEnabled(false);
            return;
            
        }
        
        if(jLabel21.getText().equals("____________"))
        {
            jLabel21.setForeground(new Color(102,0,153));
            jLabel21.setText(jTextField13.getText());
            jTextField13.setEnabled(false);
            return;
            
        }
        
        if(jLabel24.getText().equals("________"))
        {
            jLabel24.setForeground(new Color(102,0,153));
            jLabel24.setText(jTextField13.getText());
            jTextField13.setEnabled(false);
            return;
            
        }
        
        if(jLabel26.getText().equals("________"))
        {
            jLabel26.setForeground(new Color(102,0,153));
            jLabel26.setText(jTextField13.getText());
            jTextField13.setEnabled(false);
            return;
            
        }
    }//GEN-LAST:event_jTextField13MouseClicked

    private void jTextField14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField14MouseClicked
        // TODO add your handling code here:         net
        if(jLabel4.getText().equals("____________"))
        {
            jLabel4.setForeground(new Color(102,0,153));
            jLabel4.setText(jTextField14.getText());
            jTextField14.setEnabled(false);
            return;
            
        }
        
        if(jLabel6.getText().equals("____________"))
        {
            jLabel6.setForeground(new Color(102,0,153));
            jLabel6.setText(jTextField14.getText());
            jTextField14.setEnabled(false);
            return;
            
        }
        
        if(jLabel9.getText().equals("____________"))
        {
            jLabel9.setForeground(new Color(102,0,153));
            jLabel9.setText(jTextField14.getText());
            jTextField14.setEnabled(false);
            return;
            
        }
        
        if(jLabel11.getText().equals("____________"))
        {
            jLabel11.setForeground(new Color(102,0,153));
            jLabel11.setText(jTextField14.getText());
            jTextField14.setEnabled(false);
            return;
            
        }
        
        if(jLabel14.getText().equals("____________"))
        {
            jLabel14.setForeground(new Color(102,0,153));
            jLabel14.setText(jTextField14.getText());
            jTextField14.setEnabled(false);
            return;
            
        }
        
        if(jLabel16.getText().equals("________"))
        {
            jLabel16.setForeground(new Color(102,0,153));
            jLabel16.setText(jTextField14.getText());
            jTextField14.setEnabled(false);
            return;
            
        }
        
        if(jLabel19.getText().equals("____________"))
        {
            jLabel19.setForeground(new Color(102,0,153));
            jLabel19.setText(jTextField14.getText());
            jTextField14.setEnabled(false);
            return;
            
        }
        
        if(jLabel21.getText().equals("____________"))
        {
            jLabel21.setForeground(new Color(102,0,153));
            jLabel21.setText(jTextField14.getText());
            jTextField14.setEnabled(false);
            return;
            
        }
        
        if(jLabel24.getText().equals("________"))
        {
            jLabel24.setForeground(new Color(102,0,153));
            jLabel24.setText(jTextField14.getText());
            jTextField14.setEnabled(false);
            return;
            
        }
        
        if(jLabel26.getText().equals("________"))
        {
            jLabel26.setForeground(new Color(102,0,153));
            jLabel26.setText(jTextField14.getText());
            jTextField14.setEnabled(false);
            return;
            
        }
    }//GEN-LAST:event_jTextField14MouseClicked

    private void jTextField15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField15MouseClicked
        // TODO add your handling code here:            hit
        if(jLabel4.getText().equals("____________"))
        {
            jLabel4.setForeground(new Color(102,0,153));
            jLabel4.setText(jTextField15.getText());
            jTextField15.setEnabled(false);
            return;
            
        }
        
        if(jLabel6.getText().equals("____________"))
        {
            jLabel6.setForeground(new Color(102,0,153));
            jLabel6.setText(jTextField15.getText());
            jTextField15.setEnabled(false);
            return;
            
        }
        
        if(jLabel9.getText().equals("____________"))
        {
            jLabel9.setForeground(new Color(102,0,153));
            jLabel9.setText(jTextField15.getText());
            jTextField15.setEnabled(false);
            return;
            
        }
        
        if(jLabel11.getText().equals("____________"))
        {
            jLabel11.setForeground(new Color(102,0,153));
            jLabel11.setText(jTextField15.getText());
            jTextField15.setEnabled(false);
            return;
            
        }
        
        if(jLabel14.getText().equals("____________"))
        {
            jLabel14.setForeground(new Color(102,0,153));
            jLabel14.setText(jTextField15.getText());
            jTextField15.setEnabled(false);
            return;
            
        }
        
        if(jLabel16.getText().equals("________"))
        {
            jLabel16.setForeground(new Color(102,0,153));
            jLabel16.setText(jTextField15.getText());
            jTextField15.setEnabled(false);
            return;
            
        }
        
        if(jLabel19.getText().equals("____________"))
        {
            jLabel19.setForeground(new Color(102,0,153));
            jLabel19.setText(jTextField15.getText());
            jTextField15.setEnabled(false);
            return;
            
        }
        
        if(jLabel21.getText().equals("____________"))
        {
            jLabel21.setForeground(new Color(102,0,153));
            jLabel21.setText(jTextField15.getText());
            jTextField15.setEnabled(false);
            return;
            
        }
        
        if(jLabel24.getText().equals("________"))
        {
            jLabel24.setForeground(new Color(102,0,153));
            jLabel24.setText(jTextField15.getText());
            jTextField15.setEnabled(false);
            return;
            
        }
        
        if(jLabel26.getText().equals("________"))
        {
            jLabel26.setForeground(new Color(102,0,153));
            jLabel26.setText(jTextField15.getText());
            jTextField15.setEnabled(false);
            return;
            
        }
    }//GEN-LAST:event_jTextField15MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:    done
        
       
        if(jLabel4.getText().equals("mouse") && jLabel6.getText().equals("sleeping") && jLabel9.getText().equals("playing") && jLabel11.getText().equals("kill") && jLabel14.getText().equals("forgiveness") && jLabel16.getText().equals("net") && jLabel19.getText().equals("teeth") && jLabel21.getText().equals("thanked") && jLabel24.getText().equals("good") && jLabel26.getText().equals("good"))
        {
            a.correct_music();
            
            jLabel4.setForeground(new Color(50,205,50));
            jLabel6.setForeground(new Color(50,205,50));
            jLabel9.setForeground(new Color(50,205,50));
            jLabel11.setForeground(new Color(50,205,50));
            jLabel14.setForeground(new Color(50,205,50));
            jLabel16.setForeground(new Color(50,205,50));
            jLabel19.setForeground(new Color(50,205,50));
            jLabel21.setForeground(new Color(50,205,50));
            jLabel24.setForeground(new Color(50,205,50));
            jLabel26.setForeground(new Color(50,205,50));
            
            jButton4.setEnabled(true);
        }
        else
        {
            a.wrong_music();
            
            jLabel4.setForeground(Color.red);
            jLabel6.setForeground(Color.red);
            jLabel9.setForeground(Color.red);
            jLabel11.setForeground(Color.red);
            jLabel14.setForeground(Color.red);
            jLabel16.setForeground(Color.red);
            jLabel19.setForeground(Color.red);
            jLabel21.setForeground(Color.red);
            jLabel24.setForeground(Color.red);
            jLabel26.setForeground(Color.red);
            
            
        }
        
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:            retry
        if(i<=3)
        {
            jLabel4.setForeground(Color.black);
            jLabel6.setForeground(Color.black);
            jLabel9.setForeground(Color.black);
            jLabel11.setForeground(Color.black);
            jLabel14.setForeground(Color.black);
            jLabel16.setForeground(Color.black);
            jLabel19.setForeground(Color.black);
            jLabel21.setForeground(Color.black);
            jLabel24.setForeground(Color.black);
            jLabel26.setForeground(Color.black);
            
            jLabel4.setText("____________");
            jLabel6.setText("____________");
            jLabel9.setText("____________");
            jLabel11.setText("____________");
            jLabel14.setText("____________");
            jLabel16.setText("________");
            jLabel19.setText("____________");
            jLabel21.setText("____________");
            jLabel24.setText("________");
            jLabel26.setText("________");
            
            jTextField1.setEnabled(true);
            jTextField2.setEnabled(true);
            jTextField3.setEnabled(true);
            jTextField4.setEnabled(true);
            jTextField5.setEnabled(true);
            jTextField6.setEnabled(true);
            jTextField7.setEnabled(true);
            jTextField8.setEnabled(true);
            jTextField9.setEnabled(true);
            jTextField10.setEnabled(true);
            jTextField11.setEnabled(true);
            jTextField12.setEnabled(true);
            jTextField13.setEnabled(true);
            jTextField14.setEnabled(true);
            jTextField15.setEnabled(true);
            
            i++;
        }
        else
            JOptionPane.showMessageDialog(this,"Chances are over(>_<)","Alert",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:         next
        
         this.setVisible(false);
        thre1 t1=new thre1();
        thre2 t2=new thre2();
        thre3 t3=new thre3();
        
        t3.start();
        t1.start();
            
        t2.start();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:        prev
        
        this.setVisible(false);
        level_5 ll=new level_5();
        ll.jButton7.setEnabled(true);
        ll.setVisible(true);
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:         home
        this.setVisible(false);
        new home_pg().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(level_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(level_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(level_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(level_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new level_6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}

class thre1 extends Thread
{
    public void run()
    {
        try
        {
            Thread.sleep(3000);
        } catch (InterruptedException ex) 
        {
            
        }
        new rocket_gif(7);
    }
}

class thre2 extends Thread
{
    public void run()
    {
        try
        {
            Thread.sleep(6000);
        } catch (InterruptedException ex) 
        {
            
        }
        new level_7();
    }
}

class thre3 extends Thread
{
    public void run()
    {
        new coins(6);
    }
}
