/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Kirthana Balasubramanian
 */
public class level_9 extends javax.swing.JFrame {

    /** Creates new form level_9 */
    int i=1;
    correct_wrong_audio a=new correct_wrong_audio();
    
    public level_9() {
        initComponents();
        jButton3.setEnabled(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 3, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("LEVEL 9");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 86, 117, -1));

        jLabel2.setFont(new java.awt.Font("Bernard MT Condensed", 3, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("PLAY |'.'| AND PICK THE ANSWER |^_^|");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 142, 552, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/videoplay.gif"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 217, 149, 147));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel4.setText("<--    (@_@)  Click me to play the video");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 263, -1, 51));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel5.setText("1.  Where did the owl live?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 445, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jRadioButton1.setText("Beech tree");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 491, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jRadioButton2.setText("Oak tree");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 491, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jRadioButton3.setText("Pine tree ");
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 491, -1, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jRadioButton4.setText("Cottonwood tree");
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(798, 491, -1, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel6.setText("2.  What did the man said?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 538, -1, -1));

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jRadioButton5.setText("He had helped poor people.");
        getContentPane().add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 587, -1, -1));

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jRadioButton6.setText("He was an Honest man.");
        getContentPane().add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 587, -1, -1));

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jRadioButton7.setText("He had never made a mistake. ");
        getContentPane().add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 634, -1, -1));

        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jRadioButton8.setText("He was always right.");
        getContentPane().add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 634, -1, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel7.setText("3.  What did you learn from this story?");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 681, -1, -1));

        buttonGroup3.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jRadioButton9.setText("Talk less,work more.");
        getContentPane().add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 727, -1, -1));

        buttonGroup3.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jRadioButton10.setText("Speech is silver.Silence is gold.");
        getContentPane().add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 727, -1, -1));

        buttonGroup3.add(jRadioButton11);
        jRadioButton11.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jRadioButton11.setText("Always listen more.");
        getContentPane().add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 774, -1, -1));

        buttonGroup3.add(jRadioButton12);
        jRadioButton12.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jRadioButton12.setText("Talk less,but listen more.");
        getContentPane().add(jRadioButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 774, -1, -1));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 153));
        jLabel8.setText("Have you seen the video??  Then answer the questions  |$_$|");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 390, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("DONE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(831, 843, 90, 40));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("RETRY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 850, 90, 40));

        jButton3.setBackground(new java.awt.Color(51, 102, 255));
        jButton3.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("FINISH");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 530, 180, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/prev_button.jpg"))); // NOI18N
        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 160, 30));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/home_button.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 790, 70, 80));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 540, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/levelbackground.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        try
        {
            Desktop.getDesktop().open(new File("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Project\\src\\project\\story.mp4"));
        } 
        catch (IOException ex) 
        {
            
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:        next
        
        this.setVisible(false);
        thrr1 t1=new thrr1();
        thrr2 t2=new thrr2();
        
        t1.start();
            
        t2.start();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:         done
        
        if(jRadioButton2.isSelected() && jRadioButton7.isSelected() && jRadioButton12.isSelected())
        {
            jButton3.setEnabled(true);
            a.correct_music();
            
        }
        
        if(!jButton3.isEnabled())
            a.wrong_music();
        
        //Question 1
        if(jRadioButton2.isSelected())
            jRadioButton2.setForeground(Color.green);
        else 
        {
            if(jRadioButton1.isSelected())
                jRadioButton1.setForeground(Color.red);
            if(jRadioButton3.isSelected())
                jRadioButton3.setForeground(Color.red);
            if(jRadioButton4.isSelected())
                jRadioButton4.setForeground(Color.red);
        }
        
        //Question 2
        if(jRadioButton7.isSelected())
            jRadioButton7.setForeground(Color.green);
        else 
        {
            if(jRadioButton5.isSelected())
                jRadioButton5.setForeground(Color.red);
            if(jRadioButton6.isSelected())
                jRadioButton6.setForeground(Color.red);
            if(jRadioButton8.isSelected())
                jRadioButton8.setForeground(Color.red);
        }
        
        //Question 3
        if(jRadioButton12.isSelected())
            jRadioButton12.setForeground(Color.green);
        else 
        {
            if(jRadioButton9.isSelected())
                jRadioButton9.setForeground(Color.red);
            if(jRadioButton10.isSelected())
                jRadioButton10.setForeground(Color.red);
            if(jRadioButton11.isSelected())
                jRadioButton11.setForeground(Color.red);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:   retry
        
        if(i<=3)
        {
        if(jRadioButton1.getForeground().equals(Color.red))
            jRadioButton1.setForeground(Color.black);
        if(jRadioButton2.getForeground().equals(Color.red))
            jRadioButton2.setForeground(Color.black);
        if(jRadioButton3.getForeground().equals(Color.red))
            jRadioButton3.setForeground(Color.black);
        if(jRadioButton4.getForeground().equals(Color.red))
            jRadioButton4.setForeground(Color.black);
        if(jRadioButton5.getForeground().equals(Color.red))
            jRadioButton5.setForeground(Color.black);
        if(jRadioButton6.getForeground().equals(Color.red))
            jRadioButton6.setForeground(Color.black);
        if(jRadioButton7.getForeground().equals(Color.red))
            jRadioButton7.setForeground(Color.black);
        if(jRadioButton8.getForeground().equals(Color.red))
            jRadioButton8.setForeground(Color.black);
        if(jRadioButton9.getForeground().equals(Color.red))
            jRadioButton9.setForeground(Color.black);
        if(jRadioButton10.getForeground().equals(Color.red))
            jRadioButton10.setForeground(Color.black);
        if(jRadioButton11.getForeground().equals(Color.red))
            jRadioButton11.setForeground(Color.black);
        if(jRadioButton12.getForeground().equals(Color.red))
            jRadioButton12.setForeground(Color.black);
        i++;
        }
        else
            JOptionPane.showMessageDialog(this,"Chances are over(>_<)","Alert",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:    prev
        
        this.setVisible(true);
        new level_8().next.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:    home
        this.setVisible(false);
        new home_pg().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(level_9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(level_9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(level_9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(level_9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new level_9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    // End of variables declaration//GEN-END:variables

}

class thrr1 extends Thread
{
    public void run()
    {
        new coins(9);
    }
}

class thrr2 extends Thread
{
    public void run()
    {
        try
        {
            Thread.sleep(3000);
        } catch (InterruptedException ex) 
        {
            
        }
        new trophy_champion().setVisible(true);
     }
}